// Shared Tailwind theme for the main app screens (dashboard, historial, cartera, ajustes, etc.)
// Load this AFTER the CDN script: <script src="https://cdn.tailwindcss.com..."></script>
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00174b",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#adc6ff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-container": "#2170e4",
        "tertiary-container": "#00788c",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary": "#0058be",
        "secondary-fixed": "#d8e2ff",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#d7f6ff",
        "on-surface-variant": "#434655",
        "tertiary-fixed": "#acedff",
        "on-tertiary-fixed": "#001f26",
        "outline-variant": "#c3c6d7",
        "tertiary": "#005e6e",
        "on-secondary-fixed": "#001a42",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-high": "#e6e8ea",
        "primary": "#004ac6",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#003ea8",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "outline": "#737686",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-surface": "#191c1e",
        "on-primary-container": "#eeefff",
        "inverse-surface": "#2d3133",
        "surface-tint": "#0053db",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        sm: "12px",
        "margin-desktop": "48px",
        base: "8px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        xs: "4px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        display: ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
};
