// Shared Tailwind theme for auth / onboarding screens (login, registro, google, onboarding).
// Load this AFTER the CDN script: <script src="https://cdn.tailwindcss.com..."></script>
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "secondary": "#515f74",
        "secondary-fixed": "#d5e3fd",
        "secondary-fixed-dim": "#b9c7e0",
        "on-tertiary-container": "#008cc7",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#3a485c",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-container": "#001e2f",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2fd",
        "background": "#f7f9fb",
        "outline": "#76777d",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#131b2e",
        "on-primary-fixed": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001e2f",
        "on-secondary-container": "#57657b",
        "surface": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#89ceff",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-bright": "#f7f9fb",
        "on-surface-variant": "#45464d",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "tertiary-fixed": "#c9e6ff",
        "secondary-container": "#d5e3fd",
        "tertiary": "#000000",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#0d1c2f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        xl: "32px",
        gutter: "16px",
        unit: "4px",
        lg: "24px",
        md: "16px",
        xs: "4px",
        "container-margin": "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
};
